import time
print(" (z:)I/'m how do we get in?")
time.sleep(1)
print(" (ant 1#:) All you have to do is to 'Knock.'")
time.sleep(1)
print(" (z:)Well okay,(He knocked.)")
time.sleep(1)
print(" (ant 1#:) Sure,come on in!'")
time.sleep(1)
print(" (z:)Thankyou.")
time.sleep(1)
print("")
